// Base de Données Catalogue B&L STORE
// Images réelles organisées dans /img/chaussures, /img/sandales, /img/parfums

const ALL_PRODUCTS = [
  // ==========================================
  // CHAUSSURES (38 MODÈLES)
  // ==========================================
  {
    id: 'c1',
    cat: 'chaussures',
    brand: 'nike',
    name: "Nike Air Force 1 '07 All White",
    price: 25000,
    tag: 'Incontournable',
    featured: true,
    image: './img/chaussures/chaussure_nike1.jpeg',
    sizes: [39, 40, 41, 42, 43, 44, 45]
  },
  {
    id: 'c2',
    cat: 'chaussures',
    brand: 'adidas',
    name: 'Adidas Samba OG White & Core Black',
    price: 55000,
    tag: 'Best-Seller',
    featured: true,
    image: './img/chaussures/chaussure_addidas2.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c3',
    cat: 'chaussures',
    brand: 'asics',
    name: 'Asics Gel-Kayano 14 Metallic Silver',
    price: 32000,
    tag: 'Tendance',
    featured: true,
    image: './img/chaussures/Ascics2.jpeg',
    sizes: [40, 41, 42, 43, 44, 45]
  },
  {
    id: 'c4',
    cat: 'chaussures',
    brand: 'jordan',
    name: 'Air Jordan 4 Retro University Blue',
    price: 30000,
    tag: 'Culte',
    featured: true,
    image: './img/chaussures/chaussure_jordan1.jpeg',
    sizes: [40, 41, 42, 43, 44, 45]
  },
  {
    id: 'c5',
    cat: 'chaussures',
    brand: 'newbalance',
    name: 'New Balance 2002R Protection Pack Rain Cloud',
    price: 30000,
    tag: 'Édition Spéciale',
    featured: true,
    image: './img/chaussures/chaussure_newbalance1.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c6',
    cat: 'chaussures',
    brand: 'vans',
    name: 'Vans Knu Skool Chunky Suede Black & White',
    price: 33000,
    tag: 'Nouveau',
    featured: true,
    image: './img/chaussures/vans1.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c7',
    cat: 'chaussures',
    brand: 'nike',
    name: 'Nike Dunk Low Coast Blue & White',
    price: 30000,
    tag: 'Populaire',
    featured: true,
    image: './img/chaussures/chaussure_nike2.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c8',
    cat: 'chaussures',
    brand: 'nike',
    name: 'Nike Air Max Plus TN Triple Black',
    price: 30000,
    tag: 'Best-Seller',
    featured: true,
    image: './img/chaussures/chaussure_nike4.jpeg',
    sizes: [40, 41, 42, 43, 44, 45]
  },
  {
    id: 'c9',
    cat: 'chaussures',
    brand: 'asics',
    name: 'Asics Gel-NYC Cream & Oyster Grey',
    price: 30000,
    tag: 'Nouveau',
    featured: false,
    image: './img/chaussures/Ascics1.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c10',
    cat: 'chaussures',
    brand: 'asics',
    name: 'Asics Gel-NYC Pure Silver & Blue',
    price: 30000,
    tag: 'Tendance',
    featured: false,
    image: './img/chaussures/Ascics3.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c11',
    cat: 'chaussures',
    brand: 'asics',
    name: 'Asics GT-2160 White & Pure Silver',
    price: 30000,
    tag: 'Running Chic',
    featured: false,
    image: './img/chaussures/chaussure_ascics1.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c12',
    cat: 'chaussures',
    brand: 'asics',
    name: 'Asics Gel-1130 White & Midnight Navy',
    price: 30000,
    tag: 'Confort',
    featured: false,
    image: './img/chaussures/chaussure_ascics2.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c13',
    cat: 'chaussures',
    brand: 'asics',
    name: 'Asics Gel-Nimbus Triple Black',
    price: 30000,
    tag: 'Discret',
    featured: false,
    image: './img/chaussures/chaussure_ascics3.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c14',
    cat: 'chaussures',
    brand: 'asics',
    name: 'Asics Gel-Sonoma 15-50 Trail Edition',
    price: 32000,
    tag: 'Outdoor',
    featured: false,
    image: './img/chaussures/chaussure_ascics4.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c15',
    cat: 'chaussures',
    brand: 'asics',
    name: 'Asics Gel-Kayano Legacy Multi-Color',
    price: 32000,
    tag: 'Performance',
    featured: false,
    image: './img/chaussures/chaussure_ascics5.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c16',
    cat: 'chaussures',
    brand: 'adidas',
    name: 'Adidas Campus 00s Core Black & White',
    price: 55000,
    tag: 'Ultra Tendance',
    featured: false,
    image: './img/chaussures/chaussure_addidas1.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c17',
    cat: 'chaussures',
    brand: 'adidas',
    name: 'Adidas Gazelle Indoor Green & Gum',
    price: 55000,
    tag: 'Rétro Vintage',
    featured: false,
    image: './img/chaussures/chaussure_addidas3.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c18',
    cat: 'chaussures',
    brand: 'adidas',
    name: 'Adidas Superstar Classic White & Black',
    price: 25000,
    tag: 'Classique',
    featured: false,
    image: './img/chaussures/chaussure_addidas4.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c19',
    cat: 'chaussures',
    brand: 'adidas',
    name: 'Adidas Campus 00s Grey Cloud White',
    price: 30000,
    tag: 'Skate Chic',
    featured: false,
    image: './img/chaussures/chaussure_addidas5.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c20',
    cat: 'chaussures',
    brand: 'adidas',
    name: 'Adidas Handball Spezial Night Navy',
    price: 32000,
    tag: 'Tendance',
    featured: false,
    image: './img/chaussures/chaussure_addidas6.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c21',
    cat: 'chaussures',
    brand: 'adidas',
    name: 'Adidas Samba All Black Stealth Edition',
    price: 32000,
    tag: 'Épuré',
    featured: false,
    image: './img/chaussures/chaussure_addidas7.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c22',
    cat: 'chaussures',
    brand: 'newbalance',
    name: 'New Balance 9060 Sea Salt & Crisp White',
    price: 32000,
    tag: 'Chunky',
    featured: false,
    image: './img/chaussures/chaussure_newbalance2.jpeg',
    sizes: [40, 41, 42, 43, 44, 45]
  },
  {
    id: 'c23',
    cat: 'chaussures',
    brand: 'nike',
    name: 'Nike Air Max 95 OG Black & Gold Accent',
    price: 32000,
    tag: 'Streetwear',
    featured: false,
    image: './img/chaussures/chaussure_nike3.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c24',
    cat: 'chaussures',
    brand: 'nike',
    name: 'Nike Dunk Low Retro Panda Black & White',
    price: 30000,
    tag: 'Best-Seller',
    featured: false,
    image: './img/chaussures/chaussure_nike5.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c25',
    cat: 'chaussures',
    brand: 'nike',
    name: 'Nike Air Jordan 1 Low White & Wolf Grey',
    price: 30000,
    tag: 'Élégant',
    featured: false,
    image: './img/chaussures/chaussure_nike6.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c26',
    cat: 'chaussures',
    brand: 'nike',
    name: 'Nike Air Max Plus TN Gradient Blue Sky',
    price: 32000,
    tag: 'Iconique',
    featured: false,
    image: './img/chaussures/chaussure_nikeTn1.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c27',
    cat: 'chaussures',
    brand: 'nike',
    name: 'Nike Air Max Plus TN Sunset Orange',
    price: 32000,
    tag: 'Énergie',
    featured: false,
    image: './img/chaussures/chaussure_nikeTn2.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c28',
    cat: 'chaussures',
    brand: 'vans',
    name: 'Vans Old Skool Classic Black & White',
    price: 33000,
    tag: 'Skate Rétro',
    featured: false,
    image: './img/chaussures/chaussure_vans.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c29',
    cat: 'chaussures',
    brand: 'vans',
    name: 'Vans Half Cab Pro Mid Suede Black',
    price: 33000,
    tag: 'Authentique',
    featured: false,
    image: './img/chaussures/vans2.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c30',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Timberland 6-Inch Premium Boot Wheat Nubuck',
    price: 45000,
    tag: 'Robuste & Luxe',
    featured: false,
    image: './img/chaussures/chaussure_timber.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c31',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Sneaker Designer Style Dolce & Gabbana',
    price: 67000,
    tag: 'Haute Gamme',
    featured: false,
    image: './img/chaussures/chaussure_DG.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c32',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Sneaker Street Minimaliste All Black',
    price: 25000,
    tag: 'Polyvalent',
    featured: false,
    image: './img/chaussures/chaussure.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c33',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Sneaker Runner Sport White & Light Grey',
    price: 28000,
    tag: 'Confort Quotidien',
    featured: false,
    image: './img/chaussures/chaussure1.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c34',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Sneaker Urban Chic White Platform',
    price: 28000,
    tag: 'Mode',
    featured: false,
    image: './img/chaussures/chaussure2.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c35',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Mocassin Cuir Noir Prestige B&L',
    price: 35000,
    tag: 'Soirée & Affaires',
    featured: false,
    image: './img/chaussures/chaussure3.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 'c36',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Sneaker High-Top Retro Crimson Red',
    price: 32000,
    tag: 'Sportswear',
    featured: false,
    image: './img/chaussures/chaussure4.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c37',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Sneaker Casual Sport Graphite',
    price: 28000,
    tag: 'Trendy',
    featured: false,
    image: './img/chaussures/chaussure5.jpeg',
    sizes: [40, 41, 42, 43, 44]
  },
  {
    id: 'c38',
    cat: 'chaussures',
    brand: 'luxe',
    name: 'Sneaker Low Classic Monochrome',
    price: 21000,
    tag: 'Prix Doux',
    featured: false,
    image: './img/chaussures/chaussure_.jpeg',
    sizes: [39, 40, 41, 42, 43]
  },

  // ==========================================
  // SANDALES & CROCS (8 MODÈLES)
  // ==========================================
  {
    id: 's1',
    cat: 'sandales',
    type: 'crocs',
    name: 'Crocs Classic Clog Sand & Camel',
    price: 25000,
    tag: 'Best-Seller',
    featured: true,
    image: './img/sandales/crocks1.jpeg',
    sizes: [38, 39, 40, 41, 42, 43, 44]
  },
  {
    id: 's2',
    cat: 'sandales',
    type: 'crocs',
    name: 'Crocs All-Terrain Clog Slate Grey',
    price: 28000,
    tag: 'Nouveau',
    featured: true,
    image: './img/sandales/crocks2.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 's3',
    cat: 'sandales',
    type: 'crocs',
    name: 'Crocs Classic Clog Triple Black',
    price: 25000,
    tag: 'Indispensable',
    featured: true,
    image: './img/sandales/crocks3.jpeg',
    sizes: [38, 39, 40, 41, 42, 43, 44]
  },
  {
    id: 's4',
    cat: 'sandales',
    type: 'crocs',
    name: 'Crocs Echo Clog Desert Sand & Tan',
    price: 32000,
    tag: 'Design Moderne',
    featured: true,
    image: './img/sandales/crocks5.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 's5',
    cat: 'sandales',
    type: 'crocs',
    name: 'Crocs Off-Grid Clog Pure White',
    price: 28000,
    tag: 'Confort Ultime',
    featured: false,
    image: './img/sandales/crocks4.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 's6',
    cat: 'sandales',
    type: 'crocs',
    name: 'Crocs Pollex Clog Wave Collector',
    price: 35000,
    tag: 'Édition Spéciale',
    featured: false,
    image: './img/sandales/crocks6.jpeg',
    sizes: [39, 40, 41, 42, 43, 44]
  },
  {
    id: 's7',
    cat: 'sandales',
    type: 'mules',
    name: 'Mules & Pantoufles Velvet Confort B&L',
    price: 22000,
    tag: 'Détente Luxe',
    featured: false,
    image: './img/sandales/pantoufles.jpeg',
    sizes: [38, 39, 40, 41, 42, 43]
  },
  {
    id: 's8',
    cat: 'sandales',
    type: 'ballerine',
    name: 'Ballerine Cuir Souple Élégance B&L',
    price: 26000,
    tag: 'Féminin & Chic',
    featured: false,
    image: './img/sandales/balerine1.jpeg',
    sizes: [37, 38, 39, 40, 41]
  },

  // ==========================================
  // PARFUMS & FRAGRANCES (81 PARFUMS — JUSQU'À P82)
  // ==========================================
  {
    id: 'p1',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — GHOST',
    note: 'Inspiré de Black Phantom',
    price: 12000,
    tag: 'Best-Seller',
    featured: true,
    image: './img/parfums/P1.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p2',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Collection La Dorée — BACCARAT',
    note: 'Inspiré de Baccarat Rouge 540',
    price: 12000,
    tag: 'Prestige',
    featured: true,
    image: './img/parfums/P8.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p3',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Collection La Dorée — AÏSHA',
    note: 'Fragrance Royale Ambrée',
    price: 12000,
    tag: 'Incontournable',
    featured: true,
    image: './img/parfums/P10.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p4',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — AVENTUS',
    note: "Inspiré d'Aventus de Creed",
    price: 12000,
    tag: 'Mythique',
    featured: true,
    image: './img/parfums/P11.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p5',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — GRIS',
    note: 'Inspiré de Gris Dior',
    price: 12000,
    tag: 'Élégance Pure',
    featured: true,
    image: './img/parfums/P6.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p6',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Collection Privée — LIBRE Édition Intense',
    note: 'Inspiré de Libre YSL',
    price: 12000,
    tag: 'Intense',
    featured: true,
    image: './img/parfums/P13.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p7',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — ILHAM',
    note: "Inspiré d'Ilham So Oud",
    price: 12000,
    tag: 'Oriental Envoûtant',
    featured: false,
    image: './img/parfums/P2.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p8',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — PARISIEN',
    note: 'Inspiré de Scandal Homme',
    price: 12000,
    tag: 'Séduction',
    featured: false,
    image: './img/parfums/P3.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p9',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — MULA',
    note: 'Inspiré de Mula Mula Byron',
    price: 12000,
    tag: 'Gourmandise Sublime',
    featured: false,
    image: './img/parfums/P4.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p10',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — KRYPTON',
    note: 'Inspiré de Kryptonite',
    price: 12000,
    tag: 'Frais & Boisé',
    featured: false,
    image: './img/parfums/P5.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p11',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — KALIMAT',
    note: 'Inspiré de Kalemat Arabian Oud',
    price: 12000,
    tag: 'Ambré Solaire',
    featured: false,
    image: './img/parfums/P7.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p12',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée — BLEU',
    note: 'Inspiré de Bleu de Chanel',
    price: 12000,
    tag: 'Magnétique',
    featured: false,
    image: './img/parfums/P9.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p13',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Collection Privée — VIE Édition Intense',
    note: 'Inspiré de La Vie Est Belle',
    price: 12000,
    tag: 'Floral Lumineux',
    featured: false,
    image: './img/parfums/P12.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p14',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Collection Privée — MISS Édition Intense',
    note: 'Inspiré de Miss Dior',
    price: 12000,
    tag: 'Floral Romantique',
    featured: false,
    image: './img/parfums/P14.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p15',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Collection Privée — MISS Flacon & Écrin Luxe',
    note: 'Coffret Prestige & Écrin',
    price: 12000,
    tag: 'Coffret Cadeau',
    featured: false,
    image: './img/parfums/P15.jpeg',
    sizes: ['100ml + Écrin']
  },
  {
    id: 'p17',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — SOUFFLE NOUVEAU',
    note: 'Édition Blanche Cylindre Prestige Paris',
    price: 20000,
    tag: 'Nouveau',
    featured: false,
    image: './img/parfums/P17.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p18',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — GOURMANDISE',
    note: 'Notes Gourmandes & Sucrées Paris',
    price: 20000,
    tag: 'Best-Seller',
    featured: true,
    image: './img/parfums/P18.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p19',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — LAIT DE LUNE',
    note: 'Douceur Lactée, Coton & Musc Blanc',
    price: 20000,
    tag: 'Tendance',
    featured: false,
    image: './img/parfums/P19.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p20',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — POIRE GOURMANDE',
    note: 'Poire Juteuse, Sucre Glace & Vanille',
    price: 20000,
    tag: 'Fruité Chic',
    featured: false,
    image: './img/parfums/P20.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p21',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — LA VIDA LOCA',
    note: 'Sillage Solaire, Fruité & Festif',
    price: 20000,
    tag: 'Exclusif',
    featured: false,
    image: './img/parfums/P21.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p22',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — LAIT DE LUNE (Édition Écrin)',
    note: 'Musc Blanc & Accord Crème Poudré',
    price: 20000,
    tag: 'Coup de Cœur',
    featured: false,
    image: './img/parfums/P22.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p23',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Dubaï Flower — MARSHMALLOW KISS',
    note: 'Guimauve Gourmande & Nectar de Fleurs d’Orient',
    price: 44000,
    tag: 'Best-Seller Dubaï',
    featured: true,
    image: './img/parfums/P23.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p24',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Dubaï Flower — MARSHMALLOW PISTACHIO',
    note: 'Pistache Gourmande & Nuage Guimauve Fondant',
    price: 44000,
    tag: 'Tendance 2026',
    featured: true,
    image: './img/parfums/P24.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p25',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Gris Montaigne Paris — MUSC TAHARA ROUGE ABSOLU',
    note: 'Musc Purifiant Oriental & Fruits Rouges (Formule Halal)',
    price: 20000,
    tag: 'Halal & Pur',
    featured: false,
    image: './img/parfums/P25.jpeg',
    sizes: ['Coffret Crème / Extrait']
  },
  {
    id: 'p26',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — LAIT DE LUNE Flacon Prestige',
    note: 'Collection Cylindre La Folie des Délices Paris',
    price: 20000,
    tag: 'Prestige',
    featured: false,
    image: './img/parfums/P26.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p27',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Dubaï Flower — MARSHMALLOW BONBON',
    note: 'Bonbon Rose & Nuage Sucré Envoûtant',
    price: 44000,
    tag: 'Sucré & Féminin',
    featured: false,
    image: './img/parfums/P27.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p28',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Gris Montaigne Paris — MUSC TAHARA PISTACHIO GELATO',
    note: 'Glace Pistache Onctueuse & Musc Soyeux (Formule Halal)',
    price: 20000,
    tag: 'Gourmandise Pure',
    featured: false,
    image: './img/parfums/P28.jpeg',
    sizes: ['Coffret Crème / Extrait']
  },
  {
    id: 'p29',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Gris Montaigne Paris — MUSC TAHARA BARBE À PAPA',
    note: 'Sucre Filé Rose & Douceur Cotonnière (Formule Halal)',
    price: 20000,
    tag: 'Ultra Doux',
    featured: false,
    image: './img/parfums/P29.jpeg',
    sizes: ['Coffret Crème / Extrait']
  },
  {
    id: 'p30',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — SWEET MANGO',
    note: 'Mangue Exotique Juteuse & Sillage Vanillé',
    price: 20000,
    tag: 'Exotique',
    featured: false,
    image: './img/parfums/P30.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p31',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Dubaï Flower — MARSHMALLOW CRUSH',
    note: 'Explosion Sucrée Gourmande & Pêche Veloutée',
    price: 44000,
    tag: 'Nouveauté Dubaï',
    featured: false,
    image: './img/parfums/P31.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p32',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Bentley — BENTLEY FOR MEN Eau de Toilette',
    note: 'Cuir Boisé, Rhum Sombre & Feuilles de Laurier',
    price: 35000,
    tag: 'Charisme Masculin',
    featured: false,
    image: './img/parfums/P32.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p33',
    cat: 'parfums',
    subcat: 'intense',
    name: "Hermès Paris — TERRE D'HERMÈS Eau de Toilette",
    note: 'Pamplemousse, Poivre, Silex Minéral & Vétiver',
    price: 63000,
    tag: 'Luxe Iconique',
    featured: true,
    image: './img/parfums/P33.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p34',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Maison Massimo Paris — GOLD SIGNATURE (Niche Edition)',
    note: 'Bois Précieux, Ambre Doré & Muscs Impériaux',
    price: 44000,
    tag: 'Haute Parfumerie',
    featured: true,
    image: './img/parfums/P34.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p35',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Maïssa Paris — OTTOMAN LEATHER ELIXIR',
    note: "Signature d'Orient — Cuir Impérial, Safran & Épices Rares",
    price: 75000,
    tag: 'Élixir Rare',
    featured: true,
    image: './img/parfums/P35.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p36',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — PRALINÉ DATTE',
    note: 'Datte Orientale Fondante, Amande & Praliné Doré',
    price: 15000,
    tag: 'Gourmandise Orientale',
    featured: false,
    image: './img/parfums/P36.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p37',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Jean Paul Gaultier — GAULTIER DIVINE Eau de Parfum',
    note: 'Lys Solaire Majestueux, Brise Salée & Meringue Dorée',
    price: 80000,
    tag: 'Sensuel & Solaire',
    featured: true,
    image: './img/parfums/P37.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p38',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Giorgio Armani — MY WAY FLORAL Eau de Parfum',
    note: 'Fleur d’Oranger Lumineuse, Tubéreuse & Vanille Bourbon',
    price: 63000,
    tag: 'Floral Féminin',
    featured: false,
    image: './img/parfums/P38.jpeg',
    sizes: ['90ml']
  },
  {
    id: 'p39',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Prada Milano — LES INFUSIONS DE PRADA (Gingembre)',
    note: 'Infusion de Gingembre Frais, Mandarine & Cèdre Chaud',
    price: 63000,
    tag: 'Fraîcheur Chic',
    featured: false,
    image: './img/parfums/P39.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p40',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Hugo Boss & Pepe Jeans — DUO PRESTIGE (Boss & So Bold)',
    note: 'Duo Masculin Tendance : Pomme Épicée & Accord Cuir Intense',
    price: 55000,
    tag: 'Pack Duo',
    featured: false,
    image: './img/parfums/P40.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p41',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Collection Prestige Paris — ROSE BOUQUET (Écrin Luxe)',
    note: 'Rose Royale Somptueuse, Ambre Gris & Bois Précieux',
    price: 35000,
    tag: 'Coffret Prestige',
    featured: true,
    image: './img/parfums/P41.jpeg',
    sizes: ['100ml + Écrin']
  },
  {
    id: 'p42',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Azzaro — THE MOST WANTED Parfum',
    note: 'Cardamome Explosive, Toffee Fondant & Bois Ambré',
    price: 63000,
    tag: 'Séduction Pure',
    featured: true,
    image: './img/parfums/P42.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p43',
    cat: 'parfums',
    subcat: 'intense',
    name: "Hermès Paris — TERRE D'HERMÈS Pure Parfum",
    note: 'Concentré Boisé Chaud, Pamplemousse Intense & Silex Minéral',
    price: 63000,
    tag: 'Pure Parfum',
    featured: true,
    image: './img/parfums/P43.jpeg',
    sizes: ['75ml']
  },
  {
    id: 'p44',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Giorgio Armani — ACQUA DI GIÒ Parfum',
    note: 'Notes Marines Puissantes, Romarin Sauvage & Encens Noir',
    price: 80000,
    tag: 'Fraîcheur Sombre',
    featured: false,
    image: './img/parfums/P44.jpeg',
    sizes: ['75ml']
  },
  {
    id: 'p45',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Givenchy — GENTLEMAN Eau de Parfum Boisée',
    note: 'Iris Noble Poudré, Cacao Brûlé & Cèdre Blanc',
    price: 65000,
    tag: 'Élégance Suprême',
    featured: false,
    image: './img/parfums/P45.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p46',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Maison Massimo Paris — LA ROSE BLEUE (Niche Edition)',
    note: 'Rose Bleue Envoûtante & Bois Précieux en Coffret Saphir',
    price: 44000,
    tag: 'Niche Royale',
    featured: true,
    image: './img/parfums/P46.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p47',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Giorgio Armani — ACQUA DI GIÒ PROFONDO',
    note: 'Océan Abyssal, Mandarine Verte & Patchouli Minéral',
    price: 80000,
    tag: 'Bleu Abyssal',
    featured: false,
    image: './img/parfums/P47.jpeg',
    sizes: ['75ml', '125ml']
  },
  {
    id: 'p48',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Dolce & Gabbana — THE ONE FOR MEN Eau de Parfum Intense',
    note: 'Cuir Sombre, Cardamome Noire & Patchouli Magnétique',
    price: 67000,
    tag: 'Magnétique',
    featured: false,
    image: './img/parfums/P48.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p49',
    cat: 'parfums',
    subcat: 'intense',
    name: "Givenchy — L'INTERDIT ABSOLU Eau de Parfum Intense",
    note: 'Tubéreuse Fumée Noire, Tabac Blond & Fleur d’Oranger',
    price: 72000,
    tag: 'Mystérieux',
    featured: false,
    image: './img/parfums/P49.jpeg',
    sizes: ['80ml']
  },
  {
    id: 'p50',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Cartier — LA PANTHÈRE Eau de Parfum',
    note: 'Gardénia Félin Majestueux & Musc Velouté Sauvage',
    price: 80000,
    tag: 'Félin & Chic',
    featured: false,
    image: './img/parfums/P50.jpeg',
    sizes: ['75ml']
  },
  {
    id: 'p51',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Cartier — BAISER VOLÉ Eau de Parfum',
    note: 'Lys Passionné Majestueux, Feuilles Vertes & Pétales Poudrés',
    price: 80000,
    tag: 'Romance Délicate',
    featured: false,
    image: './img/parfums/P51.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p52',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Maison Massimo Paris — COEUR BLANC (Niche Edition)',
    note: 'Ambre Blanc Pur, Fleur de Coton & Santal Doux',
    price: 44000,
    tag: 'Pureté Blanche',
    featured: false,
    image: './img/parfums/P52.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p53',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Gucci — GUCCI GUILTY Absolu de Parfum Pour Homme',
    note: 'Genévrier Noir, Cyprès Boisé & Cuir Ambré Envoûtant',
    price: 67000,
    tag: 'Intense Séduction',
    featured: false,
    image: './img/parfums/P53.jpeg',
    sizes: ['60ml']
  },
  {
    id: 'p54',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Dolce & Gabbana — INTENSO Pour Homme',
    note: 'Accord Moepel Chaud, Foin Aromatique & Santal Onctueux',
    price: 67000,
    tag: 'Viril & Chaud',
    featured: false,
    image: './img/parfums/P54.jpeg',
    sizes: ['125ml']
  },
  {
    id: 'p55',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Xerjoff — AMABILE Eau de Parfum',
    note: 'Pomme Verte Croquante, Vanille Crémeuse & Cèdre Italien',
    price: 122000,
    tag: 'Haute Niche Italie',
    featured: true,
    image: './img/parfums/P55.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p56',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Maison Crivelli — OUD MARACUJÁ Extrait de Parfum',
    note: 'Fruit de la Passion Exotique & Oud Sombre Fumé Puissant',
    price: 164000,
    tag: 'Extrait Rare',
    featured: true,
    image: './img/parfums/P56.jpeg',
    sizes: ['50ml']
  },
  {
    id: 'p57',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Cartier — PASHA DE CARTIER Édition Noire Sport',
    note: 'Agrumes Rafraîchissants, Brise Marine & Cèdre Boisé',
    price: 80000,
    tag: 'Sport & Chic',
    featured: false,
    image: './img/parfums/P57.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p58',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Xerjoff Spotlight — LA CAPITALE Parfum',
    note: 'Fraise Sucrée Gourmande, Cuir Russe & Ambre Gris',
    price: 122000,
    tag: 'Chef-d’Œuvre Niche',
    featured: true,
    image: './img/parfums/P58.jpeg',
    sizes: ['50ml']
  },
  {
    id: 'p59',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Dolce & Gabbana — POUR HOMME Eau de Toilette',
    note: 'Lavande Aromatique, Tabac Fin & Bergamote Méditerranéenne',
    price: 67000,
    tag: 'Indémodable',
    featured: false,
    image: './img/parfums/P59.jpeg',
    sizes: ['125ml']
  },
  {
    id: 'p60',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Maison Massimo Paris — GOLD SIGNATURE Coffret Prestige',
    note: 'Édition Niche Prestige avec Boîtier Écrin Velours',
    price: 44000,
    tag: 'Prestige',
    featured: false,
    image: './img/parfums/P60.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p61',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Jean Paul Gaultier — LE BEAU Le Parfum',
    note: 'Noix de Coco Boisée Brûlante, Fève Tonka & Santal Ambré',
    price: 90000,
    tag: 'Hit Mondial',
    featured: true,
    image: './img/parfums/P61.jpeg',
    sizes: ['125ml']
  },
  {
    id: 'p62',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Jean Paul Gaultier — LE MALE Coffret Collector Dragon Tattoo',
    note: 'Coffret Collector Limité : EDT 125ml + Format Voyage Nomade 20ml',
    price: 100000,
    tag: 'Coffret Collector',
    featured: true,
    image: './img/parfums/P62.jpeg',
    sizes: ['125ml + 20ml']
  },
  {
    id: 'p63',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Yves Saint Laurent — Y Eau de Parfum',
    note: 'Sauge Aromatique, Géranium Frais & Bois Ambré Sombre',
    price: 70000,
    tag: 'Best-Seller Homme',
    featured: true,
    image: './img/parfums/P63.jpeg',
    sizes: ['60ml', '100ml']
  },
  {
    id: 'p64',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Soie Sublime Paris — 07 ALBA (L’aube méditerranéenne)',
    note: 'Extrait de Parfum — Fleur de Figuier & Agrumes Dorés au Soleil',
    price: 120000,
    tag: 'Extrait Solaire',
    featured: false,
    image: './img/parfums/P64.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p65',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Agathe Kattegat Paris — SIGNATURE BLANCHE',
    note: 'Floral Blanc Lumineux, Muscs Blancs & Bois Précieux',
    price: 30000,
    tag: 'Création Niche',
    featured: false,
    image: './img/parfums/P65.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p66',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Maison Massimo Paris — LA ROSE BLEUE Flacon Royal',
    note: 'Rose Majestueuse & Oud Délicat dans son Flacon d’Exception',
    price: 30000,
    tag: 'Luxe Privé',
    featured: false,
    image: './img/parfums/P66.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p67',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Soie Sublime Paris — 21 ENCENS (Le rituel nocturne)',
    note: 'Extrait de Parfum — Encens Fumé Mystique & Ambre Sombre Épicé',
    price: 120000,
    tag: 'Sillage Sombre',
    featured: false,
    image: './img/parfums/P67.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p68',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Chamalion Paris — BISSAP NIOGOMÉRA',
    note: 'Fleur d’Hibiscus Flamboyante, Gingembre Épicé & Vanille Bourbon',
    price: 30000,
    tag: 'Signature Unique',
    featured: true,
    image: './img/parfums/P68.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p69',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Marc-Antoine Barrois Paris — B683',
    note: 'Cuir Chaud Suave, Safran Royal, Poivre Noir & Santal Sombre',
    price: 80000,
    tag: 'Niche d’Auteur',
    featured: true,
    image: './img/parfums/P69.jpeg',
    sizes: ['30ml', '100ml']
  },
  {
    id: 'p70',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Jean Paul Gaultier — SCANDAL INTENSE Eau de Parfum',
    note: 'Miel Onctueux Chaud, Gardénia Sensuel & Patchouli Flamboyant',
    price: 80000,
    tag: 'Scandaleusement Sensuel',
    featured: false,
    image: './img/parfums/P70.jpeg',
    sizes: ['50ml', '80ml']
  },
  {
    id: 'p71',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée Paris — WOOD & COCO',
    note: 'Bois Précieux Chauds & Noix de Coco Crémeuse Gourmande',
    price: 20000,
    tag: 'Doux & Chaud',
    featured: false,
    image: './img/parfums/P71.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p72',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Convivium Paris — FELICCIA',
    note: 'Fleurs Lumineuses, Bergamote d’Italie & Muscs Cristallins',
    price: 20000,
    tag: 'Joie & Fraîcheur',
    featured: false,
    image: './img/parfums/P72.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p73',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Collection Kenzi Paris — IMPÉRIAL VANILLE',
    note: 'Vanille Noire de Madagascar, Ambre Solaire & Musc Chaud',
    price: 20000,
    tag: 'Gourmandise Royale',
    featured: true,
    image: './img/parfums/P73.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p74',
    cat: 'parfums',
    subcat: 'intense',
    name: 'Valentino — DONNA BORN IN ROMA Eau de Parfum',
    note: 'Jasmin Sambac Couture, Vanille Bourbon & Notes Boisées Modernes',
    price: 80000,
    tag: 'Haute Couture',
    featured: true,
    image: './img/parfums/P74.jpeg',
    sizes: ['100ml']
  },
  {
    id: 'p75',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Convivium Paris — GOURMANDISE EXTRÊME',
    note: 'Caramel Doré Fondant, Praline Croustillante & Fève Tonka Intense',
    price: 20000,
    tag: 'Extrême Sillage',
    featured: false,
    image: './img/parfums/P75.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p76',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Convivium Paris — MY DREAM',
    note: 'Bouquet Cristallin Féminin, Pivoine Blanche & Musc Céleste',
    price: 20000,
    tag: 'Rêve Poudré',
    featured: false,
    image: './img/parfums/P76.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p77',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Collection Privée Paris — OUD',
    note: 'Oud Noir Traditionnel, Ambre Brûlant & Résines Précieuses',
    price: 12000,
    tag: 'Oriental Pur',
    featured: false,
    image: './img/parfums/P77.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p78',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Convivium Paris — SKIN OF OUD',
    note: 'Oud Raffiné, Cuir Doux Sensuel & Ambre Doré Magnétique',
    price: 20000,
    tag: 'Intense Sillage',
    featured: false,
    image: './img/parfums/P78.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p79',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Convivium Paris — PENINSULA',
    note: 'Agrumes Vifs Méditerranéens, Brise Iodée & Cèdre Rafraîchissant',
    price: 20000,
    tag: 'Fraîcheur Marine',
    featured: false,
    image: './img/parfums/P79.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p80',
    cat: 'parfums',
    subcat: 'privee',
    name: 'Convivium Paris — VANILLA DREAM',
    note: 'Gousse de Vanille Crème, Sucre Roux Brûlé & Musc Doux',
    price: 20000,
    tag: 'Gourmand Absolu',
    featured: false,
    image: './img/parfums/P80.jpeg',
    sizes: ['50ml', '100ml']
  },
  {
    id: 'p81',
    cat: 'parfums',
    subcat: 'doree',
    name: 'Collection Brumes & Eaux Fraîches — BAR À BRUMES DAKAR',
    note: 'Butterfly Bloom, Fleur Sauvage, Caramelia, Coco Shine & Night Kiss',
    price: 10000,
    tag: 'Collection Brumes',
    featured: false,
    image: './img/parfums/P81.jpeg',
    sizes: ['250ml']
  },
  {
    id: 'p82',
    cat: 'parfums',
    subcat: 'privee',
    name: 'La Folie des Délices — GOURMANDISE (Coffret Cylindre & Flacon Luxe)',
    note: 'Flacon & Socle Cylindre Blanc Laqué Paris — Édition Prestige',
    price: 20000,
    tag: 'Coffret Cadeau',
    featured: false,
    image: './img/parfums/P82.jpeg',
    sizes: ['50ml + Écrin', '100ml + Écrin']
  }
];

